development:
  adapter: postgresql
  encoding: unicode
  database: Rendezvous_development
  pool: 5
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: Rendezvous_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: Rendezvous_production
  pool: 5